### ISSUE TITLE
Unable to register chat on android version 19, nor able to create new chat

### ISSUE THREAD

**Issue by shastrikikitchen** [Driftt/drift-sdk-android#17]
Hi , We are not able to initiate the chat in version 19, conversation activity keeps on loading endlessly and when trying to create new chat, its throwing the error "We're sorry, an unknown error occurred". If you could help us in understanding what is wrong with this it will be really helpful.

**Comment by imidhuntv** [comment]
For this request,
Request{method=GET, url=https://js.drift.com/embeds/30000/9fenwr278ivz.json, tag=null}

We are getting,
Response{protocol=http/1.1, code=403, message=Forbidden, url=https://js.drift.com/embeds/30000/9fenwr278ivz.json}

Response Header:
Server: CloudFront
Date: Wed, 30 May 2018 06:26:19 GMT
Content-Type: text/html
Content-Length: 556
Connection: keep-alive
X-Cache: Error from cloudfront
Via: 1.1 4bb7ba81a7fe0cf67bedfe183527a7aa.cloudfront.net (CloudFront)
X-Amz-Cf-Id: V6qkuwP1OSikjI5Xc6SqWcX09ovEKWE0L1ukGFdDamZlIvfN9Z11xA==

May be this is because of the TLS version (TLS 1.0) that API 19 is using. Please fix this.

**Comment by brianmcdon** [comment]
Hi, thanks for letting us know, this is due to a recent change in our ssl certificates, as a workaround you can call:
```ProviderInstaller.installIfNeeded(this);```
in the onCreate of your initial activity before registering with drift. Please open another issue if this still occurs.

**Comment by meshileya** [comment]
@brianmcdon , I am having this similar issue even after using ProviderInstaller.installIfNeeded(this).
